/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface CmsBlock {
  content: string;
  created_at: number;
  document_id: string;
  id: string;
  type: string;
  updated_at: number;
}

export interface CmsDocument {
  created_at: number;
  id: string;
  title: string;
  updated_at: number;
}

export interface DB {
  cms_block: CmsBlock;
  cms_document: CmsDocument;
}
