/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface CmsBlock {
  content: string;
  document_id: string;
  id: string;
  parent_id: string | null;
  position: Generated<number>;
  type: string;
}

export interface CmsDocument {
  created_at: number;
  id: string;
  title: string;
  updated_at: number;
}

export interface DB {
  cms_block: CmsBlock;
  cms_document: CmsDocument;
}
