export const ReferenceName = {
  PBV: 'PBV',
  KHBV: 'KHBV',
  ValidSince: 'ValidSince',
  legalFormEU: 'legalFormEU',
  legalFormPG: 'legalFormPG',
  legalFormKst: 'legalFormKSt',
  ValidThrough: 'ValidThrough',
  relevanceDiFin: 'relevanceDiFin',
  notPermittedFor: 'notPermittedFor',
  fiscalReference: 'fiscalReference',
  fiscalValidSince: 'fiscalValidSince',
  fiscalRequirement: 'fiscalRequirement',
  fiscalValidThrough: 'fiscalValidThrough',
  typeOperatingResult: 'typeOperatingResult',
  onlyPermittedForSoBilErgBil: 'onlyPermittedForSoBil_ErgBil',
  disabledCalcMinClassification: 'disabledCalcMinClassification',
  tradeAccountingNotPermittedFor: 'tradeAccountingNotPermittedFor',
} as const;
