/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface DmsDocument {
  id: Generated<string>;
  status: string;
}

export interface DmsRevision {
  created_at: Generated<number>;
  creator_id: string;
  document_id: string;
  file_id: string;
  id: Generated<string>;
  title: string;
}

export interface DB {
  dms_document: DmsDocument;
  dms_revision: DmsRevision;
}
