name: Create release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: semantic-release
        name: Create semantic release
        uses: master-software-gmbh/semantic-release-action@v2
